version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - DB_SCHEMA=${DB_SCHEMA}
    ports: 
      - "1433:1433"
    volumes:
      - ../var/opt/mssql/data:/var/opt/mssql/data
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${DB_PASSWORD} -Q 'SELECT 1' || exit 1"]
      interval: 1s
      retries: 30
      start_period: 2s
      timeout: 30s
  sqlserver.configurator: 
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - DB_SCHEMA=${DB_SCHEMA}
    command: /bin/bash /tmp/sqlserver/init_db.sh
    volumes:
      - ./sqlserver:/tmp/sqlserver
    depends_on:
      sqlserver:
        condition: service_healthy
  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=19411
    ports:
    - 5778:5778
    - 19411:19411
    - 16686:16686
    - 14268:14268
    - 5775:5775/udp    
    - 6831:6831/udp
    - 6832:6832/udp
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    entrypoint:
     - /usr/bin/loki
     - -config.file=/etc/config/loki.yaml
    volumes:
     - ./loki/loki.yaml:/etc/config/loki.yaml
  prometheus:
    image: prom/prometheus:v2.1.0
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus_data'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ../var/prometheus_data:/prometheus_data
    restart: always
  grafana:
    image: grafana/grafana
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
    depends_on:
      - jaeger
      - prometheus