# Authentication configuration
auth_enabled: false # Disable authentication

# Server configuration
server:
  http_listen_port: 3100 # Port for HTTP requests

# Schema configuration
schema_config:
  configs:
  - from: 2023-11-01 # Start date for the schema
    store: boltdb # Index store type
    object_store: filesystem # Object store type
    schema: v9 # Schema version
    index:
      prefix: index_ # Prefix for index names
      period: 24h # Period for index entries

# Storage configuration
storage_config:
  boltdb:
    directory: /tmp/loki/index # Directory for BoltDB index
  filesystem:
    directory: /tmp/loki/chunks # Directory for storing chunks
# Ingester configuration
ingester:
  # Write-Ahead Log configuration
  wal:
    dir: "/tmp/wal" # Directory for the Write-Ahead Log
  # Lifecycler configuration
  lifecycler:
    address: 127.0.0.1 # Address of this instance
    ring:
      kvstore:
        store: inmemory # Use in-memory store
      replication_factor: 1 # Number of replicas for the data
    final_sleep: 0s # Time to sleep before exiting after ring tokens are transferred
  chunk_idle_period: 5m # Time after which idle chunks are flushed
  chunk_retain_period: 30s # Time to retain flushed chunks in memory

# Limits configuration
limits_config:
  enforce_metric_name: false # Don't enforce metric name